safe: true
lsi: false
pygments: true
name: /blog
paginate: 5
exclude: ['Gemfile', 'Gemfile.lock']
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks