safe: true
future: true
lsi: false
name: ~/blog
highlighter: rouge
url: http://blog.jan-ahrens.eu
exclude: ['Gemfile', 'Gemfile.lock']
include: ['.well-known']
markdown: kramdown
redcarpet:
  extensions:
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
