safe: true
lsi: false
pygments: true
name: ~/blog
url: http://blog.jan-ahrens.eu
paginate: 5
exclude: ['Gemfile', 'Gemfile.lock']
include: ['.well-known']
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
